### ISSUE TITLE
For people who generate the links later with Livewire, give a JavaScript method to add event to the buttons.

### ISSUE THREAD

**Issue by ronald2wing** [kudashevs/laravel-share-buttons#1] opened 2023-08-06 19:22 UTC
Since the JavaScript methods fired on Dom load, the buttons generated later will not have the functionality.
Please create a JavaScript method for people to add events to the buttons later.

**Comment by kudashevs** [comment] 2023-08-07 18:02
Hi @ronald2wing,

Thank you for your suggestion. I need some time to think about how to implement it in a better way.
Meantime, could you please share the way how you generate the links with Livewire?

**Comment by ronald2wing** [comment] 2023-08-07 18:15
I was going to try: https://laracasts.com/discuss/channels/livewire/how-to-call-alpine-js-method-from-livewire
The default behavior is enough for me right now.

**Comment by ronald2wing** [comment] 2023-08-07 18:49
Another I will do is to use $wire.methods() to call the Livewire method in the frontend directly and then call the button update method. Thank you for looking into this.

**Comment by kudashevs** [comment] 2023-08-10 16:10
Hello @ronald2wing,

I played around with Livewire 2/3 for a couple of days and I didn't discover any issues with "DOMContentLoaded" event. Even if I render the code of the buttons through the Livewire `render()` method, the JavaScript code of the buttons works perfectly and the buttons have the expected functionality.

Could you please provide more information about your issue?
Why do you need a separate method to add events if everything works out of the box?

**Comment by ronald2wing** [comment] 2023-08-10 16:25
It could be related to using Alpine.js with Livewire. I will test it again on my local tonight. The Livewire was rerendered on the page after input changes. DOMContentLoaded is only loaded after the page is loaded, but some of my contents are loaded based on the input changes.

I am trying to share my code, but it looks like some text is being hidden in the editor:
`@if (Route::currentRouteName() === 'music-videos.show')
    @section('title', $musicVideo['title'])
@endif

<div>
    <script src="https://cdn.plyr.io/3.7.8/plyr.js"></script>
    <link rel="stylesheet" href="https://cdn.plyr.io/3.7.8/plyr.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="{{ asset('js/share-buttons.js') }}"></script>
    <div
        x-data="{
            currentMusicVideoIndex: @entangle('currentMusicVideoIndex').defer,
            musicVideo: @entangle('musicVideo').defer,
            musicVideos: @entangle('musicVideos').defer,
            get nextMusicVideoIndex() {
                let index = this.currentMusicVideoIndex;
                const keys = Object.keys(this.musicVideos);
                const keyIndex = keys.indexOf(index);
                return keys[keyIndex + 1] ?? keys[0];
            },
            setCurrentMusicVideoIndex(index) {
                index = String(index);
                if (this.musicVideos[index] === undefined) {
                    const keys = Object.keys(this.musicVideos);
                    index = keys[0];
                }
                this.currentMusicVideoIndex = index;
                this.musicVideo = this.musicVideos[index];
                window.videoPlayer.source = {
                    sources: [{
                        provider: 'youtube',
                        src: this.musicVideos[index].youtube_url,
                    }],
                    type: 'video',
                };
            },
        }"
        x-init="
            window.videoPlayer = new Plyr('#video-player', {
                autoplay: true,
                fullscreen: { enabled: false, iosNative: false },
                playsinline: true,
            });
            window.videoPlayer.on('ended', function () {
                setCurrentMusicVideoIndex(nextMusicVideoIndex);
            });
        "
        class="flex"
    >
        <div class="mr-3 overflow-auto overflow-y-scroll max-h-screen">
            <form>
                <label for="search" class="mb-2 text-sm font-medium text-gray-900 sr-only">Search</label>
                <div class="relative">
                    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                        <svg class="w-4 h-4 text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                        </svg>
                    </div>
                    <input type="search" id="search" class="block w-full p-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500" placeholder="Search" wire:model="search" wire:input.debounce.1s="setSearch">
                </div>
            </form>
            <ul role="list" class="divide-y divide-gray-200">
                @foreach ($musicVideos as $mv)
                    <li class="relative flex items-center space-x-4 py-4 pl-4 cursor-pointer"
                        :class="currentMusicVideoIndex == {{ $mv['id'] }} ? 'bg-blue-50': ''"
                        @click="setCurrentMusicVideoIndex({{ $mv['id'] }})">
                        <div class="min-w-0 flex-auto">
                            <div>
                                <div class="flex justify-between space-x-3">
                                    <div class="min-w-0 text-sm font-semibold leading-6">
                                        <span>{{ $mv['title'] . ($mv['korean_title'] ? " ({$mv['korean_title']})" : '') }}</span>
                                        <span class="text-gray-400">/</span>
                                        <span class="whitespace-nowrap">{{ $mv['artist'] }}</span>
                                    </div>
                                </div>
                                <div class="mt-3 flex items-center gap-x-2.5 text-xs leading-5 text-gray-400">
                                    <time :datetime="{{ $mv['release_date'] }}" class="flex-shrink-0 whitespace-nowrap text-sm text-gray-500">{{ $mv['release_date'] }}</time>
                                </div>
                            </div>
                            <div class="w-full border-b border-gray-400 flex last:border-b-0 items-center">
                                {!! ShareButtons::page(route('music-videos.show', $mv['slug']), "{$mv['title']} by {$mv['artist']}", [
                                        'block_prefix' => '<div id="social-links"><ul class="mt-4 flex items-center justify-center text-gray-900">',
                                        'class' => 'mr-4',
                                        ])
                                        ->copylink()
                                        ->mailto()
                                        ->facebook()
                                        ->twitter()
                                        ->pinterest()
                                        ->render();
                                !!}
                            </div>
                        </div>
                    </li>
                @endforeach
            </ul>
            @if ($isDone)
                <div class="mt-5 text-center text-sm leading-6 text-slate-500 pb-8">The End of the List</div>
            @else
                <div class="mt-5 text-center text-sm leading-6 text-slate-500 pb-8" x-intersect="$wire.loadMore()">Loading...</div>
            @endif
        </div>
        <div class="w-full">
            <div wire:ignore>
                <div id="video-player" data-plyr-provider="youtube" data-plyr-embed-id="{{ $musicVideo['youtube_url'] }}"></div>
            </div>
            <div class="min-w-0 flex-auto pt-5">
                <div class="flex justify-between space-x-3">
                    <div class="min-w-0 text-xl font-semibold leading-6">
                        <h2 class="inline-block" x-text="musicVideo.title + (musicVideo.korean_title ? `(${musicVideo.korean_title})` : '')"></h2>
                        <span class="text-gray-400">/</span>
                        <span class="whitespace-nowrap" x-text="musicVideo.artist"></span>
                        <time :datetime="musicVideo.release_date" class="flex-shrink-0 whitespace-nowrap text-sm text-gray-500" x-text="musicVideo.release_date"></time>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
`

**Comment by kudashevs** [comment] 2023-08-11 11:17
Hello @ronald2wing,

Did you get a chance to test it again?

**Comment by ronald2wing** [comment] 2023-08-11 13:32
@kudashevs 
If you scroll down to lazyload next page and click one of the Twitter: https://popcreme.com/music-videos/shooting-star
The elements will not have JavaScript popup.

**Comment by kudashevs** [comment] 2023-08-11 13:43
Hello @ronald2wing,

Now I see the issue. Thanks for sharing the link.
I'll extract a method and let you know :)

**Comment by kudashevs** [comment] 2023-08-11 17:11
@ronald2wing here is a [new version](https://github.com/kudashevs/laravel-share-buttons/blob/master/resources/assets/js/share-buttons.js) of vanilla `share-buttons.js` file with an extracted `socialButtonClickHandler` function. I've made it quite flexible, so it can be used not only directly, but also through bubbling. As an example of bubbling, it can be used like this:

```js
document.addEventListener('click', function (e) {
    socialButtonClickHandler(e);
})
```

Could you please try to play around with it and let me know if it works?
If everything is OK, I'll include it in the future release with other improvements.

**Comment by ronald2wing** [comment] 2023-08-12 00:49
Hello, the new changes do not work. Now even the default DOMContentLoaded does not set the events either. However, the events are registered in the element after inspection: popcreme.com

**Comment by kudashevs** [comment] 2023-08-12 07:18
@ronald2wing I didn't take into account additional classes on links.
I changed the code in the [share-buttons.js](https://github.com/kudashevs/laravel-share-buttons/blob/master/resources/assets/js/share-buttons.js) file and now it should work.

Could you please check it out?

**Comment by ronald2wing** [comment] 2023-08-12 12:36
I think the socialButtonClickHandler is only available in the JS file because, after file compression, the function will be renamed.

**Comment by kudashevs** [comment] 2023-08-12 14:59
@ronald2wing the compressed (minified) version works well. As I see, the issue is related with with `app.js`.

![image](https://github.com/kudashevs/laravel-share-buttons/assets/15892462/f4dcf340-7e69-465e-8c7c-46f0ad17b149)
![image](https://github.com/kudashevs/laravel-share-buttons/assets/15892462/58affe85-40c0-42de-9f04-2eda2c6006a6)
![image](https://github.com/kudashevs/laravel-share-buttons/assets/15892462/b5095f0f-85b2-4c38-8278-94e32d217425)
![image](https://github.com/kudashevs/laravel-share-buttons/assets/15892462/5eb578d7-e10b-497a-adec-48d84f4f2f7e)

As you can see in the pictures, there is a `click` event listener handled by the `app-b5a7b72e.js:5`. If I manually remove it everything works fine. So, my guess is that this event listener handles a click event too and somehow prevents a `preventDefault` to happen in `share-buttons.js`, so the click continues to be processed.

**Comment by kudashevs** [comment] 2023-08-12 15:54
@ronald2wing I added a prevention of other event listeners to the [share-buttons.js](https://github.com/kudashevs/laravel-share-buttons/blob/master/resources/assets/js/share-buttons.js) file. Theoretically, this should do the trick.

Could you please check it out?

**Comment by ronald2wing** [comment] 2023-08-12 15:55
Sure. Thank you. I will check tonight.

**Comment by ronald2wing** [comment] 2023-08-13 02:12
It works after applying the new changes and setting the function to the window because static file compression changed its name.

**Comment by kudashevs** [comment] 2023-08-13 06:15
Nice. @ronald2wing I want to close the issue, but before closing it I have two questions:
- this new method is what you wanted or you have other suggestions?
- should I delete the images of your project or should I leave them?

**Comment by ronald2wing** [comment] 2023-08-13 12:25
1) That's the new method I wanted.
2) You can leave them.

**Comment by kudashevs** [comment] 2023-08-14 21:38
The requested functionality was added in the [v4.0.0](https://github.com/kudashevs/laravel-share-buttons/releases/tag/v4.0.0) release.

@ronald2wing thank you for your contribution.

**Closed as completed by kudashevs** 2023-08-14 21:38 UTC
Labels: enhancement

**Comment by ronald2wing** [comment] 2023-08-14 21:40
Thank you as well.
